spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydb
    password: root
    username: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: #usernamehere
    password: #passwordhere
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
