server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: prod
environment: production
server:
  port: 5000
welcomeMsg: Hello from Prod
---
spring:
  config:
    activate:
      on-profile: test
environment: test
server:
  port: 4000
welcomeMsg: Hello from Test

