spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password:
  jpa:
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

redis:
  database: develhopeRedis
  password: TT5dg89gTkXCJmmarm7Usl889Ftqo30d
  host: redis-18969.c92.us-east-1-3.ec2.cloud.redislabs.com
  port: 18969


---
environment: test
redis:
  host: localhost
  port: 6380
  password:
